# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there! ğŸ‘‹ğŸ» Welcome to the COVID-19 Vaccine Finder ğŸš€
  
  Thank you and congrats ğŸ‰ for opening your very first issue in this project. A maintainer will get back to you shortly!
  Please adhere to our [Code of Conduct](https://github.com/AkhileshThite/COVID-19-VaccineFinder/blob/main/docs/code_of_conduct.md).
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to the project!
  
  Thank you and congrats ğŸ‰ for opening your first pull request. A maintainer will get back to you shortly!
  Please adhere to our [Code of Conduct](https://github.com/AkhileshThite/COVID-19-VaccineFinder/blob/main/docs/code_of_conduct.md).
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first Pull Request! ğŸ‰ All the best for your amazing open source journey ahead.âš¡ï¸
